services:
  postgres:
    image: postgres:17
    restart: unless-stopped
    env_file:
      - path: ./default.env
        required: true # default
      - path: ./.env
        required: false # override with .env if it exists
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres17:/var/lib/postgresql/data
    networks:
      - todo

  app:
    image: golang:1.24
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - todo

volumes:
  postgres17:
    name: postgres17
    driver: local

networks:
  todo:
    name: todo
    driver: bridge